package com.example.astroxplore.ui.theme

import androidx.compose.ui.graphics.Color

// Modern Twitter / X Blue Theme Palette (#1D9BF0)
val TwitterBlue = Color(0xFF1D9BF0)
val TwitterBlueDark = Color(0xFF1A8CD8)
val TwitterBlueLight = Color(0xFF71C9F8)

val AstroBlue = TwitterBlue
val AstroBlueDark = TwitterBlueDark
val AstroBlueLight = TwitterBlueLight

// Slate Palette Compatibility
val Slate50 = Color(0xFFF8FAFC)
val Slate100 = Color(0xFFF1F5F9)
val Slate200 = Color(0xFFE2E8F0)
val Slate300 = Color(0xFFCBD5E1)
val Slate400 = Color(0xFF94A3B8)
val Slate500 = Color(0xFF64748B)
val Slate600 = Color(0xFF475569)
val Slate800 = Color(0xFF1E293B)
val Slate900 = Color(0xFF0F172A)
val Slate950 = Color(0xFF020617)

// Material 3 Expressive Light Theme Tokens (High Chroma Twitter Blue)
val md_theme_light_primary = Color(0xFF1D9BF0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6EDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E32)
val md_theme_light_secondary = Color(0xFF0084D1)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0F2FE)
val md_theme_light_onSecondaryContainer = Color(0xFF002842)
val md_theme_light_tertiary = Color(0xFF0284C7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBAE6FD)
val md_theme_light_onTertiaryContainer = Color(0xFF001F2B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FAFD)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFE6EFF7)
val md_theme_light_onSurfaceVariant = Color(0xFF435364)
val md_theme_light_outline = Color(0xFFB8D3EB)
val md_theme_light_outlineVariant = Color(0xFFD3E4F4)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF0F7FE)
val md_theme_light_surfaceContainer = Color(0xFFE5F1FC)
val md_theme_light_surfaceContainerHigh = Color(0xFFD8E9F9)
val md_theme_light_surfaceContainerHighest = Color(0xFFCBE0F5)

// Material 3 Expressive Dark Theme Tokens (Cosmic Midnight Slate & Twitter Blue)
val md_theme_dark_primary = Color(0xFF1D9BF0)
val md_theme_dark_onPrimary = Color(0xFF00344F)
val md_theme_dark_primaryContainer = Color(0xFF0A3B5C)
val md_theme_dark_onPrimaryContainer = Color(0xFFCBE6FF)
val md_theme_dark_secondary = Color(0xFF53B5F5)
val md_theme_dark_onSecondary = Color(0xFF00334E)
val md_theme_dark_secondaryContainer = Color(0xFF0F4769)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4ECFC)
val md_theme_dark_tertiary = Color(0xFF38BDF8)
val md_theme_dark_onTertiary = Color(0xFF003549)
val md_theme_dark_tertiaryContainer = Color(0xFF004D68)
val md_theme_dark_onTertiaryContainer = Color(0xFFBAE6FD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF060A0F)
val md_theme_dark_onBackground = Color(0xFFF1F6FB)
val md_theme_dark_surface = Color(0xFF0B1118)
val md_theme_dark_onSurface = Color(0xFFF1F6FB)
val md_theme_dark_surfaceVariant = Color(0xFF152230)
val md_theme_dark_onSurfaceVariant = Color(0xFF8B9FB3)
val md_theme_dark_outline = Color(0xFF283D52)
val md_theme_dark_outlineVariant = Color(0xFF192837)
val md_theme_dark_surfaceContainerLowest = Color(0xFF04070B)
val md_theme_dark_surfaceContainerLow = Color(0xFF0E1620)
val md_theme_dark_surfaceContainer = Color(0xFF131D2A)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1A2737)
val md_theme_dark_surfaceContainerHighest = Color(0xFF223347)
